name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore Authentication.API dependencies
      run: dotnet restore ./src/services/GS.Authentication.API/
    - name: Restore Catalog.API dependencies
      run: dotnet restore ./src/services/GS.Catalog.API/
    - name: Restore Client.API dependencies
      run: dotnet restore ./src/services/GS.Client.API/
    - name: Restore Order.API dependencies
      run: dotnet restore ./src/services/GS.Order.API/
    - name: Restore Payment.API dependencies
      run: dotnet restore ./src/services/GS.Payment.API/
    - name: Restore Shopping.API dependencies
      run: dotnet restore ./src/services/GS.Shopping.API/
    - name: Restore WebApp.MVC dependencies
      run: dotnet restore ./src/web/GS.WebApp.MVC/
    - name: Build Authentication.API
      run: dotnet build ./src/services/GS.Authentication.API/ --configuration Release --no-restore
    - name: Build Catalog.API
      run: dotnet build ./src/services/GS.Catalog.API/ --configuration Release --no-restore
    - name: Build Client.API
      run: dotnet build ./src/services/GS.Client.API/ --configuration Release --no-restore
    - name: Build Order.API
      run: dotnet build ./src/services/GS.Order.API/ --configuration Release --no-restore
    - name: Build Payment.API
      run: dotnet build ./src/services/GS.Payment.API/ --configuration Release --no-restore
    - name: Build Shopping.API
      run: dotnet build ./src/services/GS.Shopping.API/ --configuration Release --no-restore
    - name: Build WebApp.MVC
      run: dotnet build ./src/web/GS.WebApp.MVC/ --configuration Release --no-restore
    # name: Test
    # run: dotnet test --no-build --verbosity normal
